// <auto-generated />
using Catalogues.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalogues.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Catalogues.Models.CatalogueModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Children")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Name = "Creating Digital Images",
                            Children = "Resources,Evidence,Graphic Products"
                        },
                        new
                        {
                            Name = "Resources",
                            Children = "Primary Sources,Secondary Sources"
                        },
                        new
                        {
                            Name = "Evidence",
                            Children = ""
                        },
                        new
                        {
                            Name = "Graphic Products",
                            Children = "Process,Final Product"
                        },
                        new
                        {
                            Name = "Primary Sources",
                            Children = ""
                        },
                        new
                        {
                            Name = "Secondary Sources",
                            Children = ""
                        },
                        new
                        {
                            Name = "Process",
                            Children = ""
                        },
                        new
                        {
                            Name = "Final Product",
                            Children = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
